language: perl

matrix:
  include:
  - perl: "5.28"
  - perl: "5.26"
  - perl: "5.22"
  - perl: "5.20"
    dist: trusty
  - perl: "5.16"
    dist: trusty

env:
  - "HARNESS_OPTIONS=j1 TEST_POD=1"

install:
  - "cpanm https://cpan.metacpan.org/authors/id/M/ML/MLEHMANN/EV-4.27.tar.gz"
  - "cpanm -n https://github.com/jhthorsen/linkembedder/archive/master.tar.gz"
  - "cpanm -n Test::Pod Test::Pod::Coverage"
  - "cpanm -n --installdeps ."

notifications:
  email:
    recipients:
      - jhthorsen@cpan.org
    on_failure: change
    on_success: change
