# Dependencies

# Permalinks
permalink:        /:year/:i_month/:i_day/:slug.html

# Setup
title:            Convos
tagline:          'Convos - Better group chat'
description:      'A multiuser chat application.'
url:              https://convos.by
baseurl:          /

author:
  name:           'Nordaaker'
  url:            https://twitter.com/convosby

paginate:         50
paginate_path:    blog/posts/:num
excerpt_separator: <!--more-->

# Custom vars
version:          1.1

github:
  repo:           https://github.com/Nordaaker/convos

plugins: [jekyll-paginate]
