apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "convos.fullname" . }}
  labels:
    {{- include "convos.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "convos.selectorLabels" . | nindent 6 }}
  serviceName: {{ include "convos.fullname" . }}
  replicas: 1 # There can only be one
  template:
    metadata:
      name: {{ template "convos.fullname" . }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "convos.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "convos.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: {{ .Chart.Name }}
        securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: "{{ .Values.image.pullPolicy }}"
        ports:
        - name: http
          containerPort: 3000
          protocol: TCP
        resources:
{{ toYaml .Values.resources | indent 10 }}          
        env:
        {{- if .Values.env.reverseProxy}}
        - name: CONVOS_REVERSE_PROXY
          value: "true"
        {{- end }}
{{- if .Values.extraEnv }}
{{ toYaml .Values.extraEnv | indent 8 }}
{{- end }}
        volumeMounts:
        - name: datadir
          mountPath: /data
  {{- if .Values.persistentVolume.enabled }}
  volumeClaimTemplates:
  - metadata:
      name: datadir
    spec:
      accessModes:
        - "ReadWriteOnce"
      resources:
        requests:
          storage: "{{ .Values.persistentVolume.storage }}"
    {{- if .Values.persistentVolume.storageClass }}
    {{- if (ne "-" .Values.persistentVolume.storageClass) }}
      storageClassName: "{{ .Values.persistentVolume.storageClass }}"
    {{- end }}
    {{- end }}
  {{- else }}
      - name: datadir
        emptyDir: {}
  {{- end }}
