name: convos
version: '1.2.0'
summary: Multiuser chat application that runs in your web browser
description: |
  The supported chat protocol is currently IRC.
  See http://convos.by for more details.
icon: assets/images/convos-icon.svg

type: app
grade: stable
confinement: strict # devmode or strict
architectures:
  - amd64

parts:
  convos:
    source: .
    plugin: dump
    stage:
      - -.ackrc
      - -.git
      - -.gitignore
      - -.perltidyrc
      - -.ship.conf
      - -Dockerfile
      - -script/parse-irc-message.pl
      - -parts
      - -prime
      - -stage
      - -t
    build-packages:
      - gcc
      - libc6-dev
      - make
      - libnet-ssleay-perl
      - libio-socket-ssl-perl
      - libperl5.26
      - perl-base
      - perl-modules-5.26
    stage-packages:
      - libnet-ssleay-perl
      - libio-socket-ssl-perl
      - libperl5.26
      - perl-base
      - perl-modules-5.26
    prepare: |
      set -x
      chmod +x script/snap.sh
      perl ./script/convos install

apps:
  convos:
    command: script/snap.sh
    plugs:
      - home
      - network
      - network-bind
