# https://docs.docker.com/ci-cd/github-actions/
name: Docker Image CI
on:
  push:
    branches:
      - 'docker'
      - 'master'
      - 'stable'
    tags:
      - "v*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Calculate tag name
      id: calculate_tags
      run: |
        if echo $GITHUB_REF | grep -q '^refs/tags/v'; then
          VERSION=$(echo $GITHUB_REF | cut -d/ -f3);
          TAGS='"convos/convos:'$VERSION'"]'
        elif [ "$GITHUB_REF" = "refs/heads/docker" ]; then
          TAGS='"convos/convos:alpha"]'
        elif [ "$GITHUB_REF" = "refs/heads/master" ]; then
          TAGS='"convos/convos:alpha"]'
        else
          TAGS='["convos/convos:stable"]'
        fi
        echo '::set-output name=tags::'$TAGS

    - name: Check Out Repo
      uses: actions/checkout@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./Dockerfile
        push: true
        tags: ${{ fromJson(steps.calculate_tags.outputs.tags) }}

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
